### **Numpy**

Used for multidimensional arrays also and provides inbuilt function to work with arrays

1.  NumPy is a general-purpose array-processing package
2.  Used for multidimensional arrays also and provides inbuilt function to work with arrays
3.  
fundamental package for scientific computing with Python




In [5]:
#importing numpy module
import numpy as np

In [6]:
#converting list to array
lst = [1,2,3,4,5]
arr = np.array(lst)

In [7]:
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [16]:
#multidimensional array
lst1 =[1,2,3,4,5]
lst2 =[6,7,8,9,10]
lst3 =[11,12,13,14,15]
arr = np.array([lst1,lst2,lst3])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
#shape-shows the number of row and column
arr.shape

(3, 5)

In [10]:
#reshape-means converting array row and column dimensions
arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [22]:
#Indexing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[3]

4

In [17]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
#Indexing in multidimensional array
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [21]:
arr[0:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [25]:
arr[3:]=100
print(arr)

[  1   2   3 100 100 100 100 100 100 100]


In [30]:
#arange = generating integers in a given range with provided step(default step is always 1)
arr=np.arange(0,31,step=3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27 30]


In [32]:
# linspace distributes number into equal parts within a range(start,stop,no of divisions)
np.linspace(1,10,55)

array([ 1.        ,  1.16666667,  1.33333333,  1.5       ,  1.66666667,
        1.83333333,  2.        ,  2.16666667,  2.33333333,  2.5       ,
        2.66666667,  2.83333333,  3.        ,  3.16666667,  3.33333333,
        3.5       ,  3.66666667,  3.83333333,  4.        ,  4.16666667,
        4.33333333,  4.5       ,  4.66666667,  4.83333333,  5.        ,
        5.16666667,  5.33333333,  5.5       ,  5.66666667,  5.83333333,
        6.        ,  6.16666667,  6.33333333,  6.5       ,  6.66666667,
        6.83333333,  7.        ,  7.16666667,  7.33333333,  7.5       ,
        7.66666667,  7.83333333,  8.        ,  8.16666667,  8.33333333,
        8.5       ,  8.66666667,  8.83333333,  9.        ,  9.16666667,
        9.33333333,  9.5       ,  9.66666667,  9.83333333, 10.        ])

In [36]:
#copy function and broadcasting
arr1=arr
arr1[3:]=500
print(arr1)
print(arr)

[  0   3   6 500 500 500 500 500 500 500 500]
[  0   3   6 500 500 500 500 500 500 500 500]


In [39]:
#Exploratory data analytics important condition
val = 3
arr<val
arr[arr<3]


array([0])

In [40]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
#generating ones with integer data type
np.ones(4,dtype=int)


array([1, 1, 1, 1])

In [44]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
#This function provides random distribution between 0 and 1 within given dimension
np.random.rand(2,5)

array([[0.11901761, 0.40945923, 0.10409943, 0.10693159, 0.85903585],
       [0.6545499 , 0.62602886, 0.53454127, 0.70417846, 0.26006591]])

In [49]:
arr_ex=np.random.randn(4,4)
print(arr_ex)

[[ 1.83766374  1.05263233  0.48905226  0.05243197]
 [ 2.02785531 -0.2062322  -1.40881133 -1.192274  ]
 [ 0.09635875  1.10426399  1.20918417  0.84600525]
 [ 0.61459126 -1.31639376 -0.80952509 -1.09266998]]
